export const APP_REGISTRY = [
  // SYSTEM — free, no subscription
  { id: 'bible', name: 'Bible', icon: 'BookOpen', color: '#7c3aed', category: 'faith', free: true, desc: 'Read the Holy Bible — browse by book, chapter and verse', liveUrl: 'https://theconditionofman.com/bible' },
  { id: 'bible-plans', name: 'Bible Plans', icon: 'ScrollText', color: '#6d28d9', category: 'faith', free: true, desc: 'Daily Bible reading plans with progress tracking', liveUrl: 'https://theconditionofman.com/bible-plans' },
  { id: 'verse-of-day', name: 'Verse of the Day', icon: 'Flame', color: '#f59e0b', category: 'faith', free: true, desc: 'Daily featured scripture with reflection', liveUrl: 'https://theconditionofman.com/discover' },
  { id: 'prayer-wall', name: 'Prayer Wall', icon: 'HandHeart', color: '#ec4899', category: 'faith', free: true, desc: 'Submit and intercede for community prayer requests', liveUrl: 'https://theconditionofman.com/prayer' },
  { id: 'petitions', name: 'Petitions', icon: 'ScrollText', color: '#f97316', category: 'faith', free: true, desc: 'Community petitions and advocacy board', liveUrl: 'https://theconditionofman.com/petitions' },
  { id: 'forums', name: 'Forums', icon: 'MessageSquare', color: '#0ea5e9', category: 'faith', free: true, desc: 'Faith-based discussion threads and Q&A', liveUrl: 'https://theconditionofman.com/forums' },
  { id: 'community-hub', name: 'Community', icon: 'Users', color: '#10b981', category: 'faith', free: true, desc: 'Activity feed, announcements and community hub', liveUrl: 'https://theconditionofman.com/community' },
  { id: 'live-stream', name: 'Live Stream', icon: 'Radio', color: '#ef4444', category: 'faith', free: true, desc: 'Watch live worship broadcasts and sermons', liveUrl: 'https://theconditionofman.com/live' },
  { id: 'discover-faith', name: 'Discover', icon: 'Compass', color: '#8b5cf6', category: 'faith', free: true, desc: 'Explore curated faith content and trending scriptures', liveUrl: 'https://theconditionofman.com/discover' },
  { id: 'faith-games', name: 'Bible Games', icon: 'Gamepad2', color: '#06b6d4', category: 'faith', free: true, desc: 'Interactive faith-based games and quizzes', liveUrl: 'https://theconditionofman.com/games' },
  { id: 'bookmarks', name: 'Bookmarks', icon: 'BookMarked', color: '#84cc16', category: 'faith', free: true, desc: 'Saved verses, sermons and study content', liveUrl: 'https://theconditionofman.com/profile' },
  { id: 'donate-faith', name: 'Give / Tithe', icon: 'DollarSign', color: '#22c55e', category: 'faith', free: true, desc: 'Donations, tithes and offerings', liveUrl: 'https://theconditionofman.com/donate' },
  { id: 'my-profile', name: 'My Profile', icon: 'UserCircle', color: '#a78bfa', category: 'faith', free: true, desc: 'Your account, badges and activity history', liveUrl: 'https://theconditionofman.com/profile' },
  { id: 'calculator', name: 'Calculator', icon: 'Calculator', color: '#374151', category: 'system', free: true, desc: 'Scientific calculator with history' },
  { id: 'clock', name: 'Clock', icon: 'Clock', color: '#0891b2', category: 'system', free: true, desc: 'World clock, alarms, stopwatch & timer' },
  { id: 'music', name: 'Music', icon: 'Music2', color: '#7c3aed', category: 'system', free: true, desc: 'Worship music player' },
  { id: 'calendar', name: 'Calendar', icon: 'Calendar', color: '#dc2626', category: 'system', free: true, desc: 'Personal calendar & events' },
  { id: 'privacy', name: 'Privacy Policy', icon: 'Shield', color: '#065f46', category: 'system', free: true, desc: 'Privacy policy and data usage' },
  { id: 'support', name: 'Support', icon: 'HelpCircle', color: '#1d4ed8', category: 'system', free: true, desc: 'Help center, FAQ and contact support' },
  { id: 'ephesians', name: 'Ephesians', icon: 'Globe', color: '#2563eb', category: 'system', free: true, desc: 'Revelations OS Web Browser — Chromium-powered' },
  { id: 'files', name: 'Files', icon: 'Folder', color: '#d97706', category: 'system', free: true, desc: 'File Manager' },
  { id: 'settings', name: 'Settings', icon: 'Settings2', color: '#6d28d9', category: 'system', free: true, desc: 'System Preferences' },
  { id: 'terminal', name: 'Terminal', icon: 'TerminalSquare', color: '#059669', category: 'system', free: true, desc: 'Developer Terminal + Proverbs' },
  { id: 'notepad', name: 'Notepad', icon: 'FileText', color: '#64748b', category: 'system', free: true, desc: 'Text Editor' },
  { id: 'pcscanfix', name: 'PCFixScan', icon: 'Shield', color: '#16a34a', category: 'system', free: true, desc: 'System Cleaner — FREE' },
  { id: 'appstore', name: 'App Store', icon: 'Store', color: '#7c3aed', category: 'system', free: true, desc: 'App Marketplace' },
  { id: 'celestia', name: 'Celestia', icon: 'FileStack', color: '#0e7490', category: 'system', free: true, desc: 'Office Suite — Word, Excel, PowerPoint, PDF' },
  // Subscription apps (liveUrl = embedded webview; updates auto-sync from live deployment)
  { id: 'taxflow', name: 'TaxFlow Pro', icon: 'Calculator', color: '#0284c7', category: 'finance', price: '$29/mo', trial: '14 days', free: false, desc: 'AI-powered tax preparation and bookkeeping', liveUrl: 'https://taxflow-pro.vercel.app' },
  { id: 'bowdwn', name: 'BowDwn', icon: 'ShoppingBag', color: '#ea580c', category: 'commerce', price: '$14.99/mo', trial: '7 days', free: false, desc: 'Christian streetwear ecommerce platform', liveUrl: 'https://bowdwn.vercel.app' },
  { id: 'automix', name: 'AutoMix', icon: 'Music2', color: '#7c3aed', category: 'media', price: '$9.99/mo', trial: '7 days', free: false, desc: 'Auto-mix dry vocals to production quality', liveUrl: 'https://automix.cloutkiller.com' },
  { id: 'legalvault', name: 'LegalVault Pro', icon: 'Scale', color: '#475569', category: 'legal', price: '$49/mo', trial: '14 days', free: false, desc: 'Legal document management with US legal corpus', liveUrl: 'https://legalvault-pro.vercel.app' },
  { id: 'fema', name: 'FEMA Platform', icon: 'AlertTriangle', color: '#dc2626', category: 'gov', price: 'Enterprise', trial: 'Demo', free: false, desc: 'FEMA disaster management system', liveUrl: 'https://fema-platform.vercel.app' },
  { id: 'genmed', name: 'GenMed Clinical', icon: 'Heart', color: '#db2777', category: 'health', price: '$49/mo', trial: '14 days', free: false, desc: 'Clinical management for healthcare providers', liveUrl: 'https://genmed-clinical.vercel.app' },
  { id: 'rals', name: 'RALS Unified', icon: 'Microscope', color: '#0369a1', category: 'health', price: 'Enterprise', trial: 'Demo', free: false, desc: 'Core Lab + POCT unified laboratory system', liveUrl: 'https://rals-unified.vercel.app' },
  { id: 'liquorledger', name: 'Liquor Ledger', icon: 'Wine', color: '#92400e', category: 'pos', price: '$19/mo', trial: '14 days', free: false, desc: 'Liquor store POS and inventory SaaS', liveUrl: 'https://liquorledger.vercel.app' },
  { id: 'leadforge', name: 'LeadForge', icon: 'Target', color: '#059669', category: 'marketing', price: '$39/mo', trial: '14 days', free: false, desc: 'Lead generation SaaS at leadflippers.com', liveUrl: 'https://leadflippers.com' },
  { id: 'proverbs', name: 'Proverbs', icon: 'BookOpen', color: '#6d28d9', category: 'dev', price: '$19/mo', trial: '14 days', free: false, desc: 'Developer intelligence and code scanning', liveUrl: 'https://proverbs.cloutkiller.com' },
  { id: 'ideaplanner', name: 'IdeaPlanner', icon: 'Lightbulb', color: '#b45309', category: 'productivity', price: '$4.99/mo', trial: '30 days', free: false, desc: 'Canvas mind-map and ideation tool', liveUrl: 'https://ideaplanner.vercel.app' },
  { id: 'freepost', name: 'FreePost', icon: 'Send', color: '#0d9488', category: 'marketing', price: '$24.99/mo', trial: '7 days', free: false, desc: 'AI social media automation platform', liveUrl: 'https://freepost.vercel.app' },
  { id: 'cloutkiller', name: 'CloutKiller', icon: 'TrendingUp', color: '#e11d48', category: 'marketing', price: '$14.99/mo', trial: '14 days', free: false, desc: 'Social media growth engine', liveUrl: 'https://cloutkiller.com' },
  { id: 'cloutfinder', name: 'CloutFinder', icon: 'Search', color: '#7c3aed', category: 'marketing', price: '$9.99/mo', trial: '14 days', free: false, desc: 'Audience discovery and growth tool', liveUrl: 'https://cloutfinder.com' },
  { id: 'tcom', name: 'The Condition of Man', icon: 'BookHeart', color: '#b91c1c', category: 'faith', price: '$4.99/mo', trial: '30 days', free: false, desc: 'Bible study and Christian community platform', liveUrl: 'https://theconditionofman.com' },
  { id: 'artistmanager', name: 'ArtistManager', icon: 'Mic', color: '#be185d', category: 'music', price: '$19.99/mo', trial: '14 days', free: false, desc: 'Music artist management + BMI registration', liveUrl: 'https://artistmanager.vercel.app' },
  { id: 'pawbiz', name: 'PawBiz', icon: 'PawPrint', color: '#65a30d', category: 'pets', price: '$9.99/mo', trial: '14 days', free: false, desc: 'Pet-sitting business management SaaS', liveUrl: 'https://pawbiz.cloutfinder.com' },
  { id: 'groomtrack', name: 'GroomTrack Pro', icon: 'Scissors', color: '#c2410c', category: 'pets', price: '$19/mo', trial: '14 days', free: false, desc: 'Pet grooming appointment management', liveUrl: 'https://groomtrack-pro.vercel.app' },
  { id: 'mobilemassage', name: 'Mobile Massage', icon: 'Waves', color: '#7c3aed', category: 'wellness', price: '$9.99/mo', trial: '14 days', free: false, desc: 'Mobile massage therapist booking SaaS', liveUrl: 'https://mobile-massage.vercel.app' },
  { id: 'mobilebarber', name: 'Mobile Barber', icon: 'Scissors', color: '#1d4ed8', category: 'beauty', price: '$14.99/mo', trial: '14 days', free: false, desc: 'Mobile barber scheduling platform', liveUrl: 'https://mobile-barber.vercel.app' },
  { id: 'mobilesalon', name: 'Mobile Salon', icon: 'Star', color: '#9d174d', category: 'beauty', price: '$19/mo', trial: '14 days', free: false, desc: 'Mobile salon management SaaS', liveUrl: 'https://mobile-salon.vercel.app' },
  { id: 'tradeiq', name: 'TradeIQ Desk', icon: 'BarChart2', color: '#0369a1', category: 'finance', price: '$29/mo', trial: '14 days', free: false, desc: 'Trading dashboard and auto-trader', liveUrl: 'https://tradeiqdesk.com' },
  { id: 'vybe', name: 'Vybe Engine', icon: 'Headphones', color: '#6d28d9', category: 'media', price: '$14.99/mo', trial: '14 days', free: false, desc: 'Electron DJ platform with stems + RTMP', liveUrl: 'https://vybe.cloutkiller.com' },
  { id: 'bsms', name: 'BSMS', icon: 'Briefcase', color: '#374151', category: 'business', price: '$49/mo', trial: '14 days', free: false, desc: 'Business software management services', liveUrl: 'https://bsms.vercel.app' },
  { id: 'blackwallst', name: 'Black Wall Street', icon: 'Building', color: '#78350f', category: 'community', price: 'Free', trial: 'N/A', free: true, desc: '1921 Tulsa Race Massacre commemorative portal', liveUrl: 'https://acjackson.org' },
  { id: 'schoolmgr', name: 'School Manager', icon: 'GraduationCap', color: '#065f46', category: 'education', price: '$39/mo', trial: '14 days', free: false, desc: 'School management for all roles', liveUrl: 'https://school-manager.vercel.app' },
  { id: 'contractoros', name: 'ContractorOS', icon: 'Hammer', color: '#b45309', category: 'trades', price: '$29/mo', trial: '14 days', free: false, desc: 'Contractor SaaS with 50+ pricing templates', liveUrl: 'https://handyman.cloutfinder.com' },
  { id: 'tuffbets', name: 'TuffBets', icon: 'Trophy', color: '#1e40af', category: 'sports', price: '$9.99/mo', trial: '7 days', free: false, desc: 'Sports analytics subscription platform', liveUrl: 'https://tuffbets.com' },
  { id: 'commandhq', name: 'CommandHQ', icon: 'Command', color: '#4338ca', category: 'productivity', price: '$9.99/mo', trial: '14 days', free: false, desc: 'All-in-one productivity hub', liveUrl: 'https://commandhq.vercel.app' },
  { id: 'tradeauto', name: 'Trade Auto', icon: 'Car', color: '#374151', category: 'automotive', price: '$49/mo', trial: '14 days', free: false, desc: 'Dealership management SaaS', liveUrl: 'https://tradeauto.govcoresolutions.net' },
  { id: 'govcoreerp', name: 'GovcoreERP', icon: 'Building2', color: '#1f2937', category: 'enterprise', price: '$99/mo', trial: '14 days', free: false, desc: 'All-in-one ERP with 22 modules', liveUrl: 'https://govcoresolutions.net/erp' },
  { id: 'olive', name: 'Olive POS', icon: 'ShoppingCart', color: '#3f6212', category: 'pos', price: '$49/mo', trial: '14 days', free: false, desc: 'Multi-tenant POS and inventory SaaS', liveUrl: 'https://olive.vercel.app' },
  { id: 'admincenter', name: 'Admin Center', icon: 'LayoutDashboard', color: '#4f46e5', category: 'admin', price: 'Internal', trial: 'N/A', free: true, desc: 'App metrics dashboard', liveUrl: 'https://admin-center.vercel.app' },
]

export const SYSTEM_APPS = APP_REGISTRY.filter(a => a.category === 'system')
export const RAXX_APPS = APP_REGISTRY.filter(a => a.category !== 'system')
export const OS_VERSION = '1.0.0'
export const OS_BRAND = 'Revelations OS'
